### ISSUE TITLE
Module 5 feedback

### ISSUE THREAD

**Issue by katiemwells** [Kamidala/kaichen-MADA-portfolio#3]
Hey Kai! The only problem I see with you recreation is the category names are a little scrunched together in the Republican voters bar; I know that this is due to the size of the categories so there probably isn't much you can do about them (can you change font size in ggplot?). Overall a really good recreation; I like how you exactly matched the colors!

**Comment by Kamidala** [comment]
> Hey Kai! The only problem I see with you recreation is the category names are a little scrunched together in the Republican voters bar; I know that this is due to the size of the categories so there probably isn't much you can do about them (can you change font size in ggplot?). Overall a really good recreation; I like how you exactly matched the colors!

Hi Katie! Have changed the font size, as you suggested, and I saved a PNG file with specified height/width so that the image will show up in the exact same size for each monitor, no matter the resolution. Thank you for your feedback!
