### ISSUE TITLE
flu analysis not showing

### ISSUE THREAD

**Issue by andreashandel** [Kamidala/kaichen-MADA-portfolio#4]
i can't see the flu analysis exercise on your website. looks like you got it in your YAML, so maybe you just forgot to rebuild the website before pushing to Github?

**Comment by Kamidala** [comment]
I remember building/rendering prior to pushing, but I have done so again after reading your comment. I have also edited my headers to exclude `link-external-icon: TRUE`. Please let me know if you are able to view again later today.

![image](https://user-images.githubusercontent.com/72531615/223469050-6ed860c0-6682-4bb0-8d0c-d3a4b1254b17.png)
